### ISSUE TITLE
그리디

### ISSUE THREAD

**Issue by alstjr7437** [yuyu0830/Algoholic#7]
그리디

문제 풀어오기

- [x] 김민석
- [x] 우상원
- [x] 장홍준
- [x] 손옥무

**Comment by yuyu0830** [comment]
16496 도전 갑니다
https://www.acmicpc.net/problem/16496

**Comment by yuyu0830** [comment]
해결~

**Comment by alstjr7437** [comment]
1080 -완-
https://www.acmicpc.net/problem/1080
